---
name: Spotify Connect Modified
version: dev
slug: spotify
description: Play Spotify music on your Home Assistant device
url: https://github.com/johnwelford/addon-spotify-connect
codenotary: codenotary@frenck.dev
arch:
  - aarch64
  - amd64
  - armv7
host_network: true
homeassistant_api: true
audio: true
init: false
options:
  name: HomeAssistant
  bitrate: 320
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  name: str
  bitrate: list(96|160|320)
  username: str?
  password: password?
  additional_cli_options: str?
